# **Using NumPy**

Once you've installed NumPy you can import it as a library:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [5]:
a=[1,2,3,4,5]
arr=np.array(a)
arr


array([1, 2, 3, 4, 5])

In [6]:

arr=np.array(["1",2,3,4,5])
arr

array(['1', '2', '3', '4', '5'], dtype='<U21')


Lets create a matrix using list

In [7]:
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Now lets see how matlix looks like using numpy arrays

In [8]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

there are lots of build in methods to create an array lets create some and see

np.zeros(), np.ones(), np.full()

np.arange(), np.linspace()

np.eye()

In [15]:
np.zeros([5,5])


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones([5,5])


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
np.full([5,5],7)


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
np.arange(2,11,2)

array([ 2,  4,  6,  8, 10])

In [24]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(5,5)

array([[0.10913715, 0.85012008, 0.36490342, 0.8932936 , 0.59785751],
       [0.78126641, 0.96526184, 0.68973422, 0.11568785, 0.86328155],
       [0.52027867, 0.56791107, 0.35539184, 0.05061306, 0.66359084],
       [0.2393827 , 0.6216732 , 0.47051577, 0.55939378, 0.68761576],
       [0.34815691, 0.38011219, 0.13031153, 0.26574763, 0.81534769]])

In [29]:
np.random.randint(1,100,10)

array([27,  7, 73, 44, 25, 97, 38, 33, 28, 56])

In [33]:
np.random.randint(1,100,[5,5])

array([[21, 38, 18, 15, 51],
       [47, 58,  6, 86, 74],
       [73, 16, 40, 60, 82],
       [36, 74, 68, 98, 21],
       [22, 89, 65, 94, 87]])

In [34]:
np.random.randn(5,5)

array([[-0.08828504, -1.28854707, -0.0902541 ,  1.11790409,  0.6398032 ],
       [-0.65697661,  2.49468346, -0.64375981, -0.66532194, -0.4145742 ],
       [-0.42503857, -0.70346958,  1.39836289, -0.68074125, -1.81758448],
       [ 0.74242589, -0.09766539, -0.08632034,  1.3627483 ,  0.36825209],
       [ 1.24721995, -0.43545235, -0.10021027,  2.50316436, -1.27453086]])

arange → step-based values

linspace → fixed number of values

eye → identity matrix

rand → random floats (0–1)

randint → random integers in a range

randn → random values from bell curve distribution